site_name: Day One books - A technical eBook collection by Juniper
nav:
  - Home: index.md
  - All Books:
    - Select a book: books/menu/main.md
    - The Sample Day One Book: 
      - Introduction: books/sample_book/main.md
      - FBF Use Case 1: books/sample_book/chapter1.md
      - FBF use Case 2: books/sample_book/chapter2.md
  - Download PDFs: download.md
  - About us: about.md
docs_dir: 'docs'
use_directory_urls: false
site_author: Juniper TME
theme:
  name: material
  favicon: images/favicon.ico
  logo: images/favicon.ico
  language: en
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode 
    - media: "(prefers-color-scheme: dark)"  
      scheme: slate
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
  font:
    text: Google Sans
    code: Nova
  features:
    - attr_list
    - toc.follow
    - navigation.top
    - navigation.tabs
    - navigation.instant
    - navigation.footer
    - navigation.indexes
    - search.suggest
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.action.edit
    - content.tooltips
    - content.footnote.tooltips
extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/juniper-networks
    - icon: fontawesome/brands/github
      link: https://github.com/juniper
  generator: false
copyright: "This site is maintained by HPE/Juniper Networking employees. Powered by Material for MkDocs & Pandoc"
plugins:
  - caption-per-book
  - book-enumerate
  - search:
      separator: '[\s\-\_]'
  - minify:
      minify_html: true
markdown_extensions:
  - pymdownx.extra
  - markdown_katex
  - toc:
      permalink: true
      toc_depth: 3
  - pymdownx.highlight:
      linenums: true 
      guess_lang: false  
      use_pygments: true  
extra_css:
  - https://cdn.jsdelivr.net/npm/katex@0.15.2/dist/katex.min.css
  - https://cdn.jsdelivr.net/npm/glightbox/dist/css/glightbox.min.css
  - stylesheets/extra.css
extra_javascript:
  - https://cdn.jsdelivr.net/npm/glightbox/dist/js/glightbox.min.js
  - https://cdn.jsdelivr.net/npm/katex@0.15.2/dist/katex.min.js
  - https://cdn.jsdelivr.net/npm/katex@0.15.2/dist/contrib/auto-render.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/js/all.min.js
  - js/math-render.js
  - js/extra.js
